<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <title>Анализатор страниц</title>
</head>
<body class="min-vh-100 d-flex flex-column">
    <nav class="navbar navbar-expand-md navbar-light bg-dark mb-3">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="/">Анализатор страниц</a>
            <button class="navbar-toggler btn btn-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon bg-secondary rounded"></span>
            </button>
            <div class="collapse navbar-collapse text-secondary" id="navbarNav" >
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href= <?= $router->urlFor('index') ?> >Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-secondary" href= <?= $router->urlFor('urls') ?> >Сайты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container flex-grow-1">
         <?php if ($flash): ?>
            <?php foreach ($flash as $type => $messages): ?>
                <?php if ($type === 'wrongUrl') continue; ?>
                <?php foreach ($messages as $message): ?>
                    <div class="alert alert-<?= htmlspecialchars($type) ?>">
                        <?= htmlspecialchars($message) ?>
                    </div>
                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php endif; ?>      

        <?= $content ?>
    </main>

    <footer class="border-top py-3 mt-5">
        <div class="container">
            <div class="text-center text-muted">
                <a href="https://hexlet.io" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>