<h1 class="mb-4">Сайты</h1>
<div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap" data-test="urls">
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($urls as $url): ?>
            <tr>
                <td><?=htmlspecialchars($url['id']) ?? '' ?></td>
                <td><a aria-hidden href="/urls/<?= $url['id'] ?>"><?= htmlspecialchars((string)$url['name']) ?? ''  ?></a></td>
                <td><?=htmlspecialchars((string)$url['created_at']) ?? '' ?></td>
                <td><?=htmlspecialchars((string)$url['status_code']) ?? '' ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>